#!/bin/sh

set -e

if [ -f /boot/config/interfaces ]
then
	cat /boot/config/interfaces >> /etc/network/interfaces
else
	cat <<EOF >> /etc/network/interfaces
auto eth0
iface eth0 inet dhcp
	wait-delay 15
EOF
fi

rm /etc/resolv.conf

if [ -f /boot/config/resolv.conf ]
then
	cp /boot/config/resolv.conf /etc
else
	cat <<EOF > /etc/resolv.conf
nameserver 8.8.8.8
EOF
fi
